image: gradle:5.6.4-jdk12
  
stages:
  - build  
  - test
  - clean

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"  
  MYSQL_DATABASE_NAME: hotel
  MYSQL_ROOT_PASSWORD: root

services:
  - name: mdeboute/hotel-sql:gitlab-ci
    alias: banana

connect:
  image: mdeboute/hotel-sql:gitlab-ci
  script:
  - mysql --version
  - sleep 5;
  - apt-get update && apt-get install -y mysql-client
  - mysql -h banana -uroot -proot -e "show databases; use $MYSQL_DATABASE_NAME; show tables;"

before_script:
  - echo `pwd` # debug
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script: 
    - echo "Hello, $GITLAB_USER_LOGIN !"
    - echo "This job check if the $CI_COMMIT_BRANCH branch is buildable."
    - ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: 
    - echo "This job check if every unit tests in the $CI_COMMIT_BRANCH branch pass."
    - ./gradlew check
    - ./gradlew test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
      
clean:
  stage: clean
  script:
    - echo "This job deletes the build directory."
    - ./gradlew clean

after_script:
  - echo "End CI"

